config/routes.rb
EGiftCardPdfGeneration::Application.routes.draw do

  root :to => "home#index"

  devise_for :users
  resources :users, :only => :show do
    resources :cards, :only => [:index, :show, :new, :create, :destroy] do
      match 'pdf'  => 'cards#pdf'
    end
  end

end

app/models/card.rb
class Card < ActiveRecord::Base

	belongs_to :user

	validates :vendor, :code, :amount, :user_id, :presence => true
	validates :code, :length => {:minimum => 16, :maximum => 16}

end

app/models/user.rb
class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
				 :recoverable, :rememberable, :trackable, :validatable

	# Setup accessible (or protected) attributes for your model
	attr_accessible :name, :email, :password, :password_confirmation, :remember_me

	has_many :cards

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

	before_filter :authenticate_user!

	def index
	end

	def new
		@user = current_user
		@card = Card.new(:user_id => @user)
	end

	def create
		@card = Card.new(params[:card])

		if @card.save
			flash[:success] = '<strong>Card</strong> was successfully created.'.html_safe
			redirect_to root_path
		else
			if @card.errors.any?
				flashmessage = String.new
				@card.errors.each do |attribute, msg|
					flashmessage += '<strong>' + attribute.to_s + '</strong> ' + msg + '; '
				end
				flash[:error] = flashmessage.html_safe
			end
			redirect_to new_user_card_path
		end
	end

	def show
		@card = Card.find(params[:id])
		respond_to do |format|
			format.html
			format.pdf do
				render :pdf => "card", # pdf will download as my_pdf.pdf
					:layout => 'pdf', # uses views/layouts/pdf.haml
					:show_as_html => params[:debug].present? # renders html version if you set debug=true in URL
			end
		end
	end

	def destroy
	end

	def pdf
		format.pdf do
			render :pdf => "file_name"
		end
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		if user_signed_in?
			@cards = current_user.cards.all
		end
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authenticate_user!

	def show
		@card = User.find(params[:id]).cards.all
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/index.html.haml
%h1 Users::Cards#index
%p Find me in app/views/cards/index.html.haml

app/views/cards/new.html.haml
%h2 Add new card
= form_for [@user, @card], :html => {:multipart => true} do |f|
	%fieldset
		= f.hidden_field :user_id, :value => current_user.id
		.clearfix
			= f.label :vendor
			.input
				= f.text_field :vendor
		.clearfix
			= f.label :code
			.input
				= f.text_field :code
				%span.help-block Should have 16 numbers
		.clearfix
			= f.label :amount
			.input.input-prepend
				%span.add-on $
				= f.text_field :amount
		.clearfix
			= f.submit "Add card", :class => "btn"

%p= link_to 'Back to cards', root_path

app/views/cards/pdf.html.haml
%h1 Users::Cards#pdf
%p Find me in app/views/cards/pdf.html.haml

app/views/cards/show.html.haml
%h3= @card.code
%p
	%strong Vendor
	= @card.vendor
%p
	%strong Amount
	= @card.amount

%p= link_to 'Get pdf', user_card_path(:user_id => current_user, :id => @card.id, :format => :pdf)

%p= link_to 'Back to cards', root_path

app/views/cards/show.pdf.haml
%h3= @card.code
%p
	%strong Vendor
	= @card.vendor
%p
	%strong Amount
	= @card.amount


-#%p= link_to 'Back to cards', root_path

app/views/home/index.html.haml
%h3 Home
- if @cards
	- @cards.each do |card|
		%p Card: #{link_to card.code, user_card_path(:user_id => current_user.id, :id => card.id)}
	= link_to "Add new card", new_user_card_path(:user_id => current_user)

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title E Gift Card Pdf Generation
		%meta{:charset => "utf-8"}
		%meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
		%meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
		= stylesheet_link_tag :application
		= javascript_include_tag :application
		= csrf_meta_tags
	%body{:class => params[:controller]}
		#container.container
			%header
				%nav
					%ul.hmenu
						= render 'shared/navigation'
					- flash.each do |name, msg|
						.alert-message{:class => name}
							%a.close{:href => "#"} ×
							%p= msg
				= yield
			%footer

app/views/layouts/pdf.haml
!!!
%html
	%head
		%title E Gift Card Pdf Generation
		%meta{:charset => "utf-8"}
		%meta{"http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1"}
		%meta{:name => "viewport", :content => "width=device-width, initial-scale=1, maximum-scale=1"}
		= csrf_meta_tags
	%body{:class => params[:controller]}
		#container.container
			%header
				- flash.each do |name, msg|
					.alert-message{:class => name}
						%a.close{:href => "#"} ×
						%p= msg
				= yield
			%footer

app/views/shared/_navigation.html.haml
- if user_signed_in?
  %li
    = link_to('Logout', destroy_user_session_path, :method=>'delete')
- else
  %li
    = link_to('Login', new_user_session_path)
- if user_signed_in?
  %li
    = link_to('Edit account', edit_user_registration_path)
- else
  %li
    = link_to('Sign up', new_user_registration_path)